compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_TOKEN}"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
